#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

if [ -n "$(find . -newer enlight*.xpi ! -path '*.git*')" ] ; then
    exec < /dev/tty
    printf 'Did you run |jpm xpi|? [y/N]: '
    read R
    [ "$R" = "y" ] || (echo "Aborting commit." && exit 1)
fi
